In [1]:
!pip install requests

Requirement already satisfied: requests in c:\users\91995\anaconda3\lib\site-packages (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\91995\anaconda3\lib\site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\91995\anaconda3\lib\site-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\91995\anaconda3\lib\site-packages (from requests) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\91995\anaconda3\lib\site-packages (from requests) (2024.12.14)

In [2]:
import requests

In [3]:
URL = "https://stephen-king-api.onrender.com/api/books"

res = requests.get(URL)

In [6]:
data = res.json()

In [14]:
import pandas as pd

df= pd.json_normalize(data["data"])
df = df[['id','Title','Year','ISBN']]

In [15]:
df

    id          Title  Year               ISBN
0    1         Carrie  1974  978-0-385-08695-0
1    2    Salem's Lot  1975  978-0-385-00751-1
2    3    The Shining  1977  978-0-385-12167-5
3    4           Rage  1977  978-0-451-07645-8
4    5      The Stand  1978  978-0-385-12168-2
..  ..            ...   ...                ...
58  59   The Outsider  2018  978-1-50118-098-9
59  60      Elevation  2018  978-1-98210-231-9
60  61  The Institute  2019  978-1-98211-056-7
61  62          Later  2021  978-1-78909-649-1
62  63  Billy Summers  2021  978-1-982-17361-6

[63 rows x 4 columns]

In [13]:
URL = "https://api.jikan.moe/v4/anime?q=新世紀&sfw"

res = requests.get(URL)

In [14]:
data = res.json()

In [16]:
import pandas as pd

df= pd.json_normalize(data["data"])

In [17]:
import pandas as pd
 
df = pd.DataFrame(data["data"])
print(df)

    mal_id                                                url  \
0       30  https://myanimelist.net/anime/30/Shinseiki_Eva...
1       32  https://myanimelist.net/anime/32/Shinseiki_Eva...
2       31  https://myanimelist.net/anime/31/Shinseiki_Eva...
3       92  https://myanimelist.net/anime/92/Kidou_Shinsei...
4      764  https://myanimelist.net/anime/764/Zoids_Shinse...
5     1391  https://myanimelist.net/anime/1391/Future_GPX_...
6     2770  https://myanimelist.net/anime/2770/SF_Shinseik...
7     1392  https://myanimelist.net/anime/1392/Future_GPX_...
8     1393  https://myanimelist.net/anime/1393/Future_GPX_...
9     1395  https://myanimelist.net/anime/1395/Future_GPX_...
10    1394  https://myanimelist.net/anime/1394/Future_GPX_...
11    2065  https://myanimelist.net/anime/2065/Gall_Force_...
12    3764  https://myanimelist.net/anime/3764/Chouon_Sens...
13    1396  https://myanimelist.net/anime/1396/Future_GPX_...
14    9759  https://myanimelist.net/anime/9759/Future_GPX_...
15   63534  https://myanimelist.net/anime/63534/Shinseiki_...
16   63534  https://myanimelist.net/anime/63534/Shinseiki_...
17   21547  https://myanimelist.net/anime/21547/Shin_Choub...
18   22657  https://myanimelist.net/anime/22657/Shin_Seiki...
19   63094  https://myanimelist.net/anime/63094/Xin_Baoxia...
20   62589  https://myanimelist.net/anime/62589/Blue_Lock_...
21   62534  https://myanimelist.net/anime/62534/Shin_Tenni...
22   62534  https://myanimelist.net/anime/62534/Shin_Tenni...
23   62508  https://myanimelist.net/anime/62508/Doraemon_M...
24   62277  https://myanimelist.net/anime/62277/Gintama_Mo...

                                               images  \
0   {'jpg': {'image_url': 'https://myanimelist.net...
1   {'jpg': {'image_url': 'https://myanimelist.net...
2   {'jpg': {'image_url': 'https://myanimelist.net...
3   {'jpg': {'image_url': 'https://myanimelist.net...
4   {'jpg': {'image_url': 'https://myanimelist.net...
5   {'jpg': {'image_url': 'https://myanimelist.net...
6   {'jpg': {'image_url': 'https://myanimelist.net...
7   {'jpg': {'image_url': 'https://myanimelist.net...
8   {'jpg': {'image_url': 'https://myanimelist.net...
9   {'jpg': {'image_url': 'https://myanimelist.net...
10  {'jpg': {'image_url': 'https://myanimelist.net...
11  {'jpg': {'image_url': 'https://myanimelist.net...
12  {'jpg': {'image_url': 'https://myanimelist.net...
13  {'jpg': {'image_url': 'https://myanimelist.net...
14  {'jpg': {'image_url': 'https://myanimelist.net...
15  {'jpg': {'image_url': 'https://myanimelist.net...
16  {'jpg': {'image_url': 'https://myanimelist.net...
17  {'jpg': {'image_url': 'https://myanimelist.net...
18  {'jpg': {'image_url': 'https://myanimelist.net...
19  {'jpg': {'image_url': 'https://myanimelist.net...
20  {'jpg': {'image_url': 'https://myanimelist.net...
21  {'jpg': {'image_url': 'https://myanimelist.net...
22  {'jpg': {'image_url': 'https://myanimelist.net...
23  {'jpg': {'image_url': 'https://myanimelist.net...
24  {'jpg': {'image_url': 'https://myanimelist.net...

                                              trailer  approved  \
0   {'youtube_id': None, 'url': None, 'embed_url':...      True
1   {'youtube_id': None, 'url': None, 'embed_url':...      True
2   {'youtube_id': None, 'url': None, 'embed_url':...      True
3   {'youtube_id': None, 'url': None, 'embed_url':...      True
4   {'youtube_id': None, 'url': None, 'embed_url':...      True
5   {'youtube_id': None, 'url': None, 'embed_url':...      True
6   {'youtube_id': None, 'url': None, 'embed_url':...      True
7   {'youtube_id': None, 'url': None, 'embed_url':...      True
8   {'youtube_id': None, 'url': None, 'embed_url':...      True
9   {'youtube_id': None, 'url': None, 'embed_url':...      True
10  {'youtube_id': None, 'url': None, 'embed_url':...      True
11  {'youtube_id': None, 'url': None, 'embed_url':...      True
12  {'youtube_id': None, 'url': None, 'embed_url':...      True
13  {'youtube_id': None, 'url': None, 'embed_url':...      True
14  {'youtube_id': None, 'url': None, 'embed_url':...      True
15  {'youtube_id': None, 'url': None, 'embed_url':...      True
16  {'youtube_id': None, 'url': None, 'embed_url':...      True
17  {'youtube_id': None, 'url': None, 'embed_url':...      True
18  {'youtube_id': None, 'url': None, 'embed_url':...      True
19  {'youtube_id': None, 'url': None, 'embed_url':...      True
20  {'youtube_id': None, 'url': None, 'embed_url':...      True
21  {'youtube_id': None, 'url': None, 'embed_url':...      True
22  {'youtube_id': None, 'url': None, 'embed_url':...      True
23  {'youtube_id': None, 'url': None, 'embed_url':...      True
24  {'youtube_id': None, 'url': None, 'embed_url':...      True

                                               titles  \
0   [{'type': 'Default', 'title': 'Shinseiki Evang...
1   [{'type': 'Default', 'title': 'Shinseiki Evang...
2   [{'type': 'Default', 'title': 'Shinseiki Evang...
3   [{'type': 'Default', 'title': 'Kidou Shinseiki...
4   [{'type': 'Default', 'title': 'Zoids Shinseiki...
5   [{'type': 'Default', 'title': 'Future GPX Cybe...
6   [{'type': 'Default', 'title': 'SF Shinseiki Le...
7   [{'type': 'Default', 'title': 'Future GPX Cybe...
8   [{'type': 'Default', 'title': 'Future GPX Cybe...
9   [{'type': 'Default', 'title': 'Future GPX Cybe...
10  [{'type': 'Default', 'title': 'Future GPX Cybe...
11  [{'type': 'Default', 'title': 'Gall Force: New...
12  [{'type': 'Default', 'title': 'Chouon Senshi B...
13  [{'type': 'Default', 'title': 'Future GPX Cybe...
14  [{'type': 'Default', 'title': 'Future GPX Cybe...
15  [{'type': 'Default', 'title': 'Shinseiki Evang...
16  [{'type': 'Default', 'title': 'Shinseiki Evang...
17  [{'type': 'Default', 'title': 'Shin Choubakuma...
18  [{'type': 'Default', 'title': 'Shin Seikimatsu...
19  [{'type': 'Default', 'title': 'Xin Baoxiao Xia...
20  [{'type': 'Default', 'title': 'Blue Lock (Shin...
21  [{'type': 'Default', 'title': 'Shin Tennis no ...
22  [{'type': 'Default', 'title': 'Shin Tennis no ...
23  [{'type': 'Default', 'title': 'Doraemon Movie ...
24  [{'type': 'Default', 'title': 'Gintama Movie 3...

                                                title  \
0                                Shinseiki Evangelion
1   Shinseiki Evangelion Movie: Air/Magokoro wo, K...
2          Shinseiki Evangelion Movie: Shi to Shinsei
3                            Kidou Shinseiki Gundam X
4                                Zoids Shinseiki/Zero
5                            Future GPX Cyber Formula
6                                SF Shinseiki Lensman
7                         Future GPX Cyber Formula 11
8                       Future GPX Cyber Formula Zero
9                        Future GPX Cyber Formula Sin
10                      Future GPX Cyber Formula Saga
11                                Gall Force: New Era
12            Chouon Senshi Borgman 2: Shinseiki 2058
13       Future GPX Cyber Formula: Early Days Renewal
14                  Future GPX Cyber Formula Graffiti
15             Shinseiki Evangelion (Shinsaku Series)
16             Shinseiki Evangelion (Shinsaku Series)
17          Shin Choubakumatsu Shounen Seiki Takamaru
18                 Shin Seikimatsu: Yatsuto no Souguu
19                               Xin Baoxiao Xiaoyuan
20                            Blue Lock (Shin Series)
21  Shin Tennis no Oujisama: U-17 World Cup Kessho...
22  Shin Tennis no Oujisama: U-17 World Cup Kessho...
23  Doraemon Movie 45: Shin Nobita no Kaitei Kiganjou
24                Gintama Movie 3: Yoshiwara Daienjou

                                        title_english  \
0                             Neon Genesis Evangelion
1      Neon Genesis Evangelion: The End of Evangelion
2            Neon Genesis Evangelion: Death & Rebirth
3                                  After War Gundam X
4                                  Zoids: New Century
5                                                None
6                                                None
7                                                None
8                                                None
9                                                None
10                                               None
11                                               None
12          Sonic Soldier Borgman 2: New Century 2058
13                                               None
14                                               None
15               Neon Genesis Evangelion (New Series)
16               Neon Genesis Evangelion (New Series)
17                                               None
18                          Encounters with that Kind
19                                       Funny School
20                                               None
21                                               None
22                                               None
23  Doraemon the Movie 2026: New Nobita and the Ca...
24                                               None

                        title_japanese  \
0                          新世紀エヴァンゲリオン
1       新世紀エヴァンゲリオン劇場版 Air / まごころを, 君に
2                 新世紀エヴァンゲリオン劇場版 シト新生
3                           機動新世紀ガンダムX
4                            ゾイド新世紀／ゼロ
5                     新世紀GPXサイバーフォーミュラ
6                          SF新世紀 レンズマン
7                   新世紀GPXサイバーフォーミュラ11
8                 新世紀GPXサイバーフォーミュラZERO
9                  新世紀ＧＰＸサイバーフォーミュラＳＩＮ
10                新世紀ＧＰＸサイバーフォーミュラＳＡＧＡ
11                          ガルフォース新世紀編
12       超音戦士ボーグマン2 [SECOND] -新世紀2058-
13  新世紀ＧＰＸサイバーフォーミュラ EARLYDAYS RENEWAL
14             新世紀GPXサイバーフォーミュラ グラフィティ
15                  新世紀エヴァンゲリオン 新作シリーズ
16                  新世紀エヴァンゲリオン 新作シリーズ
17                       新・超幕末少年世紀タカマル
18                          新世紀末 奴との遭遇
19                           新爆笑校园 第一季
20                        ブルーロック 新シリーズ
21   新テニスの王子様 U-17 WORLD CUP 決勝メンバー決定戦
22   新テニスの王子様 U-17 WORLD CUP 決勝メンバー決定戦
23                 映画ドラえもん 新・のび太の海底鬼岩城
24                     新劇場版 銀魂 -吉原大炎上-

                                       title_synonyms  ...  season    year  \
0                            [NGE, Evangelion (1995)]  ...    fall  1995.0
1   [Shinseiki Evangelion Gekijouban: The End of E...  ...    None     NaN
2   [Shinseiki Evangelion Gekijouban: Shi to Shins...  ...    None     NaN
3   [After War Gundam X, Mobile New Century Gundam X]  ...  spring  1996.0
4   [Zoids New Century/Zero, Zoids: New Century Zero]  ...  winter  2001.0
5   [Cyber Formula: Shinseiki-GPX, Shinseiki GPX C...  ...  spring  1991.0
6   [Science Fiction New Century Lensman, Lensman ...  ...    None     NaN
7   [Shinseiki-GPX Cyber Formula 11, Shinseiki GPX...  ...    None     NaN
8                  [Shinseiki-GPX Cyber Formula Zero]  ...    None     NaN
9                    [Shinseki-GPX Cyber Formula Sin]  ...    None     NaN
10                  [Shinseki-GPX Cyber Formula Saga]  ...    None     NaN
11                       [Gall Force: Shin Seiki Hen]  ...    None     NaN
12                         [Borgman II, Borgman 2058]  ...    None     NaN
13    [Shinseiki-GPX Cyber Formula EARYLDAYS RENEWAL]  ...    None     NaN
14             [Shinseiki GPX Cyber Formula Graffiti]  ...    None     NaN
15                                              [NGE]  ...    None     NaN
16                                              [NGE]  ...    None     NaN
17  [Shin Cho Bakumatsu Shonen Seiki Takamaru, Chi...  ...    None     NaN
18  [Shin Seikimatsu Yatsuto no Sogu, End of the N...  ...    None     NaN
19                                                 []  ...    None     NaN
20                                                 []  ...    None     NaN
21                                                 []  ...    fall  2026.0
22                                                 []  ...    fall  2026.0
23                                                 []  ...    None     NaN
24             [Gintama Movie 3: Yoshiwara in Flames]  ...    None     NaN

                                            broadcast  \
0   {'day': 'Wednesdays', 'time': '18:30', 'timezo...
1   {'day': None, 'time': None, 'timezone': None, ...
2   {'day': None, 'time': None, 'timezone': None, ...
3   {'day': 'Fridays', 'time': '17:00', 'timezone'...
4   {'day': None, 'time': None, 'timezone': None, ...
5   {'day': None, 'time': None, 'timezone': None, ...
6   {'day': None, 'time': None, 'timezone': None, ...
7   {'day': None, 'time': None, 'timezone': None, ...
8   {'day': None, 'time': None, 'timezone': None, ...
9   {'day': None, 'time': None, 'timezone': None, ...
10  {'day': None, 'time': None, 'timezone': None, ...
11  {'day': None, 'time': None, 'timezone': None, ...
12  {'day': None, 'time': None, 'timezone': None, ...
13  {'day': None, 'time': None, 'timezone': None, ...
14  {'day': None, 'time': None, 'timezone': None, ...
15  {'day': None, 'time': None, 'timezone': None, ...
16  {'day': None, 'time': None, 'timezone': None, ...
17  {'day': None, 'time': None, 'timezone': None, ...
18  {'day': None, 'time': None, 'timezone': None, ...
19  {'day': None, 'time': None, 'timezone': None, ...
20  {'day': None, 'time': None, 'timezone': None, ...
21  {'day': None, 'time': None, 'timezone': None, ...
22  {'day': None, 'time': None, 'timezone': None, ...
23  {'day': None, 'time': None, 'timezone': None, ...
24  {'day': None, 'time': None, 'timezone': None, ...

                                            producers  \
0   [{'mal_id': 16, 'type': 'anime', 'name': 'TV T...
1   [{'mal_id': 16, 'type': 'anime', 'name': 'TV T...
2   [{'mal_id': 16, 'type': 'anime', 'name': 'TV T...
3   [{'mal_id': 55, 'type': 'anime', 'name': 'TV A...
4   [{'mal_id': 3087, 'type': 'anime', 'name': 'Sh...
5                                                  []
6   [{'mal_id': 159, 'type': 'anime', 'name': 'Kod...
7                                                  []
8                                                  []
9                                                  []
10                                                 []
11  [{'mal_id': 72, 'type': 'anime', 'name': 'Artm...
12                                                 []
13                                                 []
14                                                 []
15                                                 []
16                                                 []
17                                                 []
18                                                 []
19                                                 []
20                                                 []
21                                                 []
22                                                 []
23                                                 []
24  [{'mal_id': 1889, 'type': 'anime', 'name': 'Wa...

                                            licensors  \
0   [{'mal_id': 97, 'type': 'anime', 'name': 'ADV ...
1   [{'mal_id': 783, 'type': 'anime', 'name': 'GKI...
2   [{'mal_id': 783, 'type': 'anime', 'name': 'GKI...
3   [{'mal_id': 217, 'type': 'anime', 'name': 'Noz...
4   [{'mal_id': 119, 'type': 'anime', 'name': 'VIZ...
5   [{'mal_id': 233, 'type': 'anime', 'name': 'Ban...
6   [{'mal_id': 2278, 'type': 'anime', 'name': 'Ha...
7                                                  []
8                                                  []
9                                                  []
10                                                 []
11  [{'mal_id': 284, 'type': 'anime', 'name': 'Cen...
12                                                 []
13                                                 []
14                                                 []
15                                                 []
16                                                 []
17                                                 []
18                                                 []
19                                                 []
20                                                 []
21                                                 []
22                                                 []
23                                                 []
24                                                 []

                                              studios  \
0   [{'mal_id': 6, 'type': 'anime', 'name': 'Gaina...
1   [{'mal_id': 6, 'type': 'anime', 'name': 'Gaina...
2   [{'mal_id': 6, 'type': 'anime', 'name': 'Gaina...
3   [{'mal_id': 14, 'type': 'anime', 'name': 'Sunr...
4   [{'mal_id': 27, 'type': 'anime', 'name': 'Xebe...
5   [{'mal_id': 14, 'type': 'anime', 'name': 'Sunr...
6   [{'mal_id': 11, 'type': 'anime', 'name': 'Madh...
7   [{'mal_id': 14, 'type': 'anime', 'name': 'Sunr...
8   [{'mal_id': 14, 'type': 'anime', 'name': 'Sunr...
9   [{'mal_id': 14, 'type': 'anime', 'name': 'Sunr...
10  [{'mal_id': 14, 'type': 'anime', 'name': 'Sunr...
11  [{'mal_id': 48, 'type': 'anime', 'name': 'AIC'...
12  [{'mal_id': 242, 'type': 'anime', 'name': 'Ash...
13  [{'mal_id': 14, 'type': 'anime', 'name': 'Sunr...
14  [{'mal_id': 14, 'type': 'anime', 'name': 'Sunr...
15  [{'mal_id': 47, 'type': 'anime', 'name': 'Khar...
16  [{'mal_id': 47, 'type': 'anime', 'name': 'Khar...
17  [{'mal_id': 7, 'type': 'anime', 'name': 'J.C.S...
18  [{'mal_id': 291, 'type': 'anime', 'name': 'CoM...
19                                                 []
20                                                 []
21                                                 []
22                                                 []
23  [{'mal_id': 247, 'type': 'anime', 'name': 'Shi...
24  [{'mal_id': 1258, 'type': 'anime', 'name': 'Ba...

                                               genres explicit_genres  \
0   [{'mal_id': 5, 'type': 'anime', 'name': 'Avant...              []
1   [{'mal_id': 5, 'type': 'anime', 'name': 'Avant...              []
2   [{'mal_id': 8, 'type': 'anime', 'name': 'Drama...              []
3   [{'mal_id': 2, 'type': 'anime', 'name': 'Adven...              []
4   [{'mal_id': 2, 'type': 'anime', 'name': 'Adven...              []
5   [{'mal_id': 2, 'type': 'anime', 'name': 'Adven...              []
6   [{'mal_id': 1, 'type': 'anime', 'name': 'Actio...              []
7   [{'mal_id': 8, 'type': 'anime', 'name': 'Drama...              []
8   [{'mal_id': 8, 'type': 'anime', 'name': 'Drama...              []
9   [{'mal_id': 8, 'type': 'anime', 'name': 'Drama...              []
10  [{'mal_id': 8, 'type': 'anime', 'name': 'Drama...              []
11  [{'mal_id': 24, 'type': 'anime', 'name': 'Sci-...              []
12  [{'mal_id': 1, 'type': 'anime', 'name': 'Actio...              []
13  [{'mal_id': 8, 'type': 'anime', 'name': 'Drama...              []
14  [{'mal_id': 1, 'type': 'anime', 'name': 'Actio...              []
15  [{'mal_id': 5, 'type': 'anime', 'name': 'Avant...              []
16  [{'mal_id': 5, 'type': 'anime', 'name': 'Avant...              []
17  [{'mal_id': 1, 'type': 'anime', 'name': 'Actio...              []
18  [{'mal_id': 4, 'type': 'anime', 'name': 'Comed...              []
19  [{'mal_id': 4, 'type': 'anime', 'name': 'Comed...              []
20  [{'mal_id': 30, 'type': 'anime', 'name': 'Spor...              []
21  [{'mal_id': 30, 'type': 'anime', 'name': 'Spor...              []
22  [{'mal_id': 30, 'type': 'anime', 'name': 'Spor...              []
23  [{'mal_id': 4, 'type': 'anime', 'name': 'Comed...              []
24  [{'mal_id': 1, 'type': 'anime', 'name': 'Actio...              []

                                               themes  \
0   [{'mal_id': 18, 'type': 'anime', 'name': 'Mech...
1   [{'mal_id': 18, 'type': 'anime', 'name': 'Mech...
2   [{'mal_id': 18, 'type': 'anime', 'name': 'Mech...
3   [{'mal_id': 18, 'type': 'anime', 'name': 'Mech...
4   [{'mal_id': 18, 'type': 'anime', 'name': 'Mech...
5   [{'mal_id': 3, 'type': 'anime', 'name': 'Racin...
6   [{'mal_id': 29, 'type': 'anime', 'name': 'Spac...
7   [{'mal_id': 3, 'type': 'anime', 'name': 'Racin...
8   [{'mal_id': 3, 'type': 'anime', 'name': 'Racin...
9   [{'mal_id': 3, 'type': 'anime', 'name': 'Racin...
10  [{'mal_id': 3, 'type': 'anime', 'name': 'Racin...

In [18]:
df

,mal_id,url,images,trailer,approved,titles,title,title_english,title_japanese,title_synonyms,...,season,year,broadcast,producers,licensors,studios,genres,explicit_genres,themes,demographics
0,30,https://myanimelist.net/anime/30/Shinseiki_Eva...,{'jpg': {'image_url': 'https://myanimelist.net...,"{'youtube_id': None, 'url': None, 'embed_url':...",True,"[{'type': 'Default', 'title': 'Shinseiki Evang...",Shinseiki Evangelion,Neon Genesis Evangelion,新世紀エヴァンゲリオン,"[NGE, Evangelion (1995)]",...,fall,1995.0,"{'day': 'Wednesdays', 'time': '18:30', 'timezo...","[{'mal_id': 16, 'type': 'anime', 'name': 'TV T...","[{'mal_id': 97, 'type': 'anime', 'name': 'ADV ...","[{'mal_id': 6, 'type': 'anime', 'name': 'Gaina...","[{'mal_id': 5, 'type': 'anime', 'name': 'Avant...",[],"[{'mal_id': 18, 'type': 'anime', 'name': 'Mech...",[]
1,32,https://myanimelist.net/anime/32/Shinseiki_Eva...,{'jpg': {'image_url': 'https://myanimelist.net...,"{'youtube_id': None, 'url': None, 'embed_url':...",True,"[{'type': 'Default', 'title': 'Shinseiki Evang...","Shinseiki Evangelion Movie: Air/Magokoro wo, K...",Neon Genesis Evangelion: The End of Evangelion,"新世紀エヴァンゲリオン劇場版 Air / まごころを, 君に",[Shinseiki Evangelion Gekijouban: The End of E...,...,None,NaN,"{'day': None, 'time': None, 'timezone': None, ...","[{'mal_id': 16, 'type': 'anime', 'name': 'TV T...","[{'mal_id': 783, 'type': 'anime', 'name': 'GKI...","[{'mal_id': 6, 'type': 'anime', 'name': 'Gaina...","[{'mal_id': 5, 'type': 'anime', 'name': 'Avant...",[],"[{'mal_id': 18, 'type': 'anime', 'name': 'Mech...",[]
2,31,https://myanimelist.net/anime/31/Shinseiki_Eva...,{'jpg': {'image_url': 'https://myanimelist.net...,"{'youtube_id': None, 'url': None, 'embed_url':...",True,"[{'type': 'Default', 'title': 'Shinseiki Evang...",Shinseiki Evangelion Movie: Shi to Shinsei,Neon Genesis Evangelion: Death & Rebirth,新世紀エヴァンゲリオン劇場版 シト新生,[Shinseiki Evangelion Gekijouban: Shi to Shins...,...,None,NaN,"{'day': None, 'time': None, 'timezone': None, ...","[{'mal_id': 16, 'type': 'anime', 'name': 'TV T...","[{'mal_id': 783, 'type': 'anime', 'name': 'GKI...","[{'mal_id': 6, 'type': 'anime', 'name': 'Gaina...","[{'mal_id': 8, 'type': 'anime', 'name': 'Drama...",[],"[{'mal_id': 18, 'type': 'anime', 'name': 'Mech...",[]
3,92,https://myanimelist.net/anime/92/Kidou_Shinsei...,{'jpg': {'image_url': 'https://myanimelist.net...,"{'youtube_id': None, 'url': None, 'embed_url':...",True,"[{'type': 'Default', 'title': 'Kidou Shinseiki...",Kidou Shinseiki Gundam X,After War Gundam X,機動新世紀ガンダムX,"[After War Gundam X, Mobile New Century Gundam X]",...,spring,1996.0,"{'day': 'Fridays', 'time': '17:00', 'timezone'...","[{'mal_id': 55, 'type': 'anime', 'name': 'TV A...","[{'mal_id': 217, 'type': 'anime', 'name': 'Noz...","[{'mal_id': 14, 'type': 'anime', 'name': 'Sunr...","[{'mal_id': 2, 'type': 'anime', 'name': 'Adven...",[],"[{'mal_id': 18, 'type': 'anime', 'name': 'Mech...",[]
4,764,https://myanimelist.net/anime/764/Zoids_Shinse...,{'jpg': {'image_url': 'https://myanimelist.net...,"{'youtube_id': None, 'url': None, 'embed_url':...",True,"[{'type': 'Default', 'title': 'Zoids Shinseiki...",Zoids Shinseiki/Zero,Zoids: New Century,ゾイド新世紀／ゼロ,"[Zoids New Century/Zero, Zoids: New Century Zero]",...,winter,2001.0,"{'day': None, 'time': None, 'timezone': None, ...","[{'mal_id': 3087, 'type': 'anime', 'name': 'Sh...","[{'mal_id': 119, 'type': 'anime', 'name': 'VIZ...","[{'mal_id': 27, 'type': 'anime', 'name': 'Xebe...","[{'mal_id': 2, 'type': 'anime', 'name': 'Adven...",[],"[{'mal_id': 18, 'type': 'anime', 'name': 'Mech...",[]
5,1391,https://myanimelist.net/anime/1391/Future_GPX_...,{'jpg': {'image_url': 'https://myanimelist.net...,"{'youtube_id': None, 'url': None, 'embed_url':...",True,"[{'type': 'Default', 'title': 'Future GPX Cybe...",Future GPX Cyber Formula,None,新世紀GPXサイバーフォーミュラ,"[Cyber Formula: Shinseiki-GPX, Shinseiki GPX C...",...,spring,1991.0,"{'day': None, 'time': None, 'timezone': None, ...",[],"[{'mal_id': 233, 'type': 'anime', 'name': 'Ban...","[{'mal_id': 14, 'type': 'anime', 'name': 'Sunr...","[{'mal_id': 2, 'type': 'anime', 'name': 'Adven...",[],"[{'mal_id': 3, 'type': 'anime', 'name': 'Racin...",[]
6,2770,https://myanimelist.net/anime/2770/SF_Shinseik...,{'jpg': {'image_url': 'https://myanimelist.net...,"{'youtube_id': None, 'url': None, 'embed_url':...",True,"[{'type': 'Default', 'title': 'SF Shinseiki Le...",SF Shinseiki Lensman,None,SF新世紀 レンズマン,"[Science Fiction New Century Lensman, Lensman ...",...,None,NaN,"{'day': None, 'time': None, 'timezone': None, ...","[{'mal_id': 159, 'type': 'anime', 'name': 'Kod...","[{'mal_id': 2278, 'type': 'anime', 'name': 'Ha...","[{'mal_id': 11, 'type': 'anime', 'name': 'Madh...","[{'mal_id': 1, 'type': 'anime', 'name': 'Actio...",[],"[{'mal_id': 29, 'type': 'anime', 'name': 'Spac...",[]
7,1392,https://myanimelist.net/anime/1392/Future_GPX_...,{'jpg': {'image_url': 'https://myanimelist.net...,"{'youtube_id': None, 'url': None, 'embed_url':...",True,"[{'type': 'Default', 'title': 'Future GPX Cybe...",Future GPX Cyber Formula 11,None,新世紀GPXサイバーフォーミュラ11,"[Shinseiki-GPX Cyber Formula 11, Shinseiki GPX...",...,None,NaN,"{'day': None, 'time': None, 'timezone': None, ...",[],[],"[{'mal_id': 14, 'type': 'anime', 'name': 'Sunr...","[{'mal_id': 8, 'type': 'anime', 'name': 'Drama...",[],"[{'mal_id': 3, 'type': 'anime', 'name': 'Racin...",[]
8,1393,https://myanimelist.net/anime/1393/Future_GPX_...,{'jpg': {'image_url': 'https://myanimelist.net...,"{'youtube_id': None, 'url': None, 'embed_url':...",True,"[{'type': 'Default', 'title': 'Future GPX Cybe...",Future GPX Cyber Formula Zero,None,新世紀GPXサイバーフォーミュラZERO,[Shinseiki-GPX Cyber Formula Zero],...,None,NaN,"{'day': None, 'time': None, 'timezone': None, ...",[],[],"[{'mal_id': 14, 'type': 'anime', 'name': 'Sunr...","[{'mal_id': 8, 'type': 'anime', 'name': 'Drama...",[],"[{'mal_id': 3, 'type': 'anime', 'name': 'Racin...",[]
9,1395,https://myanimelist.net/anime/1395/Future_GPX_...,{'jpg': {'image_url': 'https://myanimelist.net...,"{'youtube_id': None, 'url': None, 'embed_url':...",True,"[{'type': 'Default', 'title': 'Future GPX Cybe...",Future GPX Cyber Formula Sin,None,新世紀ＧＰＸサイバーフォーミュラＳＩＮ,[Shinseki-GPX Cyber Formula Sin],...,None,NaN,"{'day': None, 'time': None, 'timezone': None, ...",[],[],"[{'mal_id': 14, 'type': 'anime', 'name': 'Sunr...","[{'mal_id': 8, 'type': 'anime', 'name': 'Drama...",[],"[{'mal_id': 3, 'type': 'anime', 'name': 'Racin...",[]
10,1394,https://myanimelist.net/anime/1394/Future_GPX_...,{'jpg': {'image_url': 'https://myanimelist.net...,"{'youtube_id': None, 'url': None, 'embed_url':...",True,"[{'type': 'Default', 'title': 'Future GPX Cybe...",Future GPX Cyber Formula Saga,None,新世紀ＧＰＸサイバーフォーミュラＳＡＧＡ,[Shinseki-GPX Cyber Formula Saga],...,None,NaN,"{'day': None, 'time': None, 'timezone': None, ...",[],[],"[{'mal_id': 14, 'type': 'anime', 'name': 'Sunr...","[{'mal_id': 8, 'type': 'anime', 'name': 'Drama...",[],"[{'mal_id': 3, 'type': 'anime', 'name': 'Racin...",[]
11,2065,https://myanimelist.net/anime/2065/Gall_Force_...,{'jpg': {'image_url': 'https://myanimelist.net...,"{'youtube_id': None, 'url': None, 'embed_url':...",True,"[{'type': 'Default', 'title': 'Gall Force: New...",Gall Force: New Era,None,ガルフォース新世紀編,[Gall Force: Shin Seiki Hen],...,None,NaN,"{'day': None, 'time': None, 'timezone': None, ...","[{'mal_id': 72, 'type': 'anime', 'name': 'Artm...","[{'mal_id': 284, 'type': 'anime', 'name': 'Cen...","[{'mal_id': 48, 'type': 'anime', 'name': 'AIC'...","[{'mal_id': 24, 'type': 'anime', 'name': 'Sci-...",[],"[{'mal_id': 18, 'type': 'anime', 'name': 'Mech...",[]
12,3764,https://myanimelist.net/anime/3764/Chouon_Sens...,{'jpg': {'image_url': 'https://myanimelist.net...,"{'youtube_id': None, 'url': None, 'embed_url':...",True,"[{'type': 'Default', 'title': 'Chouon Senshi B...",Chouon Senshi Borgman 2: Shinseiki 2058,Sonic Soldier Borgman 2: New Century 2058,超音戦士ボーグマン2 [SECOND] -新世紀2058-,"[Borgman II, Borgman 2058]",...,None,NaN,"{'day': None, 'time': None, 'timezone': None, ...",[],[],"[{'mal_id': 242, 'type': 'anime', 'name': 'Ash...","[{'mal_id': 1, 'type': 'anime', 'name': 'Actio...",[],"[{'mal_id': 6, 'type': 'anime', 'name': 'Mytho...",[]
13,1396,https://myanimelist.net/anime/1396/Future_GPX_...,{'jpg': {'image_url': 'https://myanimelist.net...,"{'youtube_id': None, 'url': None, 'embed_url':...",True,"[{'type': 'Default', 'title': 'Future GPX Cybe...",Future GPX Cyber Formula: Early Days Renewal,None,新世紀ＧＰＸサイバーフォーミュラ EARLYDAYS RENEWAL,[Shinseiki-GPX Cyber Formula EARYLDAYS RENEWAL],...,None,NaN,"{'day': None, 'time': None, 'timezone': None, ...",[],[],"[{'mal_id': 14, 'type': 'anime', 'name': 'Sunr...","[{'mal_id': 8, 'type': 'anime', 'name': 'Drama...",[],[],[]
14,9759,https://myanimelist.net/anime/9759/Future_GPX_...,{'jpg': {'image_url': 'https://myanimelist.net...,"{'youtube_id': None, 'url': None, 'embed_url':...",True,"[{'type': 'Default', 'title': 'Future GPX Cybe...",Future GPX Cyber Formula Graffiti,None,新世紀GPXサイバーフォーミュラ グラフィティ,[Shinseiki GPX Cyber Formula Graffiti],...,None,NaN,"{'day': None, 'time': None, 'timezone': None, ...",[],[],"[{'mal_id': 14, 'type': 'anime', 'name': 'Sunr...","[{'mal_id': 1, 'type': 'anime', 'name': 'Actio...",[],"[{'mal_id': 3, 'type': 'anime', 'name': 'Racin...",[]
15,63534,https://myanimelist.net/anime/63534/Shinseiki_...,{'jpg': {'image_url': 'https://myanimelist.net...,"{'youtube_id': None, 'url': None, 'embed_url':...",True,"[{'type': 'Default', 'title': 'Shinseiki Evang...",Shinseiki Evangelion (Shinsaku Series),Neon Genesis Evangelion (New Series),新世紀エヴァンゲリオン 新作シリーズ,[NGE],...,None,NaN,"{'day': None, 'time': None, 'timezone': None, ...",[],[],"[{'mal_id': 47, 'type': 'anime', 'name': 'Khar...","[{'mal_id': 5, 'type': 'anime', 'name': 'Avant...",[],"[{'mal_id': 18, 'type': 'anime', 'name': 'Mech...",[]
16,63534,https://myanimelist.net/anime/63534/Shinseiki_...,{'jpg': {'image_url': 'https://myanimelist.net...,"{'youtube_id': None, 'url': None, 'embed_url':...",True,"[{'type': 'Default', 'title': 'Shinseiki Evang...",Shinseiki Evangelion (Shinsaku Series),Neon Genesis Evangelion (New Series),新世紀エヴァンゲリオン 新作シリーズ,[NGE],...,None,NaN,"{'day': None, 'time': None, 'timezone': None, ...",[],[],"[{'mal_id': 47, 'type': 'anime', 'name': 'Khar...","[{'mal_id': 5, 'type': 'anime', 'name': 'Avant...",[],"[{'mal_id': 18, 'type': 'anime', 'name': 'Mech...",[]
17,21547,https://myanimelist.net/anime/21547/Shin_Choub...,{'jpg': {'image_url': 'https://myanimelist.net...,"{'youtube_id': None, 'url': None, 'embed_url':...",True,"[{'type': 'Default', 'title': 'Shin Choubakuma...",Shin Choubakumatsu Shounen Seiki Takamaru,None,新・超幕末少年世紀タカマル,"[Shin Cho Bakumatsu Shonen Seiki Takamaru, Chi...",...,None,NaN,"{'day': None, 'time': None, 'timezone': None, ...",[],[],"[{'mal_id': 7, 'type': 'anime', 'name': 'J.C.S...","[{'mal_id': 1, 'type': 'anime', 'name': 'Actio...",[],[],[]
18,22657,https://myanimelist.net/anime/22657/Shin_Seiki...,{'jpg': {'image_url': 'https://myanimelist.net...,"{'youtube_id': None, 'url': None, 'embed_url':...",True,"[{'type': 'Default', 'title': 'Shin Seikimatsu...",Shin Seikimatsu: Yatsuto no Souguu,Encounters with that Kind,新世紀末 奴との遭遇,"[Shin Seikimatsu Yatsuto no Sogu, End of the N...",...,None,NaN,"{'day': None, 'time': None, 'timezone': None, ...",[],[],"[{'mal_id': 291, 'type': 'anime', 'name': 'CoM...","[{'mal_id': 4, 'type': 'anime', 'name': 'Comed...",[],[],[]
19,63094,https://myanimelist.net/anime/63094/Xin_Baoxia...,{'jpg': {'image_url': 'https://myanimelist.net...,"{'youtube_id': None, 'url': None, 'embed_url':...",True,"[{'type': 'Default', 'title': 'Xin Baoxiao Xia...",Xin Baoxiao Xiaoyuan,Funny School,新爆笑校园 第一季,[],...,None,NaN,"{'day': None, 'time': None, 'timezone': None, ...",[],[],[],"[{'mal_id': 4, 'type': 'anime', 'name': 'Comed...",[],[],"[{'mal_id': 15, 'type': 'anime', 'name': 'Kids..."
20,62589,https://myanimelist.net/anime/62589/Blue_Lock_...,{'jpg': {'image_url': 'https://myanimelist.net...,"{'youtube_id': None, 'url': None, 'embed_url':...",True,"[{'type': 'Default', 'title': 'Blue Lock (Shin...",Blue Lock (Shin Series),None,ブルーロック 新シリーズ,[],...,None,NaN,"{'day': None, 'time': None, 'timezone': None, ...",[],[],[],"[{'mal_id': 30, 'type': 'anime', 'name': 'Spor...",[],"[{'mal_id': 77, 'type': 'anime', 'name': 'Team...","[{'mal_id': 27, 'type': 'anime', 'name': 'Shou..."
21,62534,https://myanimelist.net/anime/62534/Shin_Tenni...,{'jpg': {'image_url': 'https://myanimelist.net...,"{'youtube_id': None, 'url': None, 'embed_url':...",True,"[{'type': 'Default', 'title': 'Shin Tennis no ...",Shin Tennis no Oujisama: U-17 World Cup Kessho...,None,新テニスの王子様 U-17 WORLD CUP 決勝メンバー決定戦,[],...,fall,2026.0,"{'day': None, 'time': None, 'timezone': None, ...",[],[],[],"[{'mal_id': 30, 'type': 'anime', 'name': 'Spor...",[],"[{'mal_id': 23, 'type': 'anime', 'name': 'Scho...","[{'mal_id': 27, 'type': 'anime', 'name': 'Shou..."
22,62534,https://myanimelist.net/anime/62534/Shin_Tenni...,{'jpg': {'image_url': 'https://myanimelist.net...,"{'youtube_id': None, 'url': None, 'embed_url':...",True,"[{'type': 'Default', 'title': 'Shin Tennis no ...",Shin Tennis no Oujisama: U-17 World Cup Kessho...,None,新テニスの王子様 U-17 WORLD CUP 決勝メンバー決定戦,[],...,fall,2026.0,"{'day': None, 'time': None, 'timezone': None, ...",[],[],[],"[{'mal_id': 30, 'type': 'anime', 'name': 'Spor...",[],"[{'mal_id': 23, 'type': 'anime', 'name': 'Scho...","[{'mal_id': 27, 'type': 'anime', 'name': 'Shou..."
23,62508,https://myanimelist.net/anime/62508/Doraemon_M...,{'jpg': {'image_url': 'https://myanimelist.net...,"{'youtube_id': None, 'url': None, 'embed_url':...",True,"[{'type': 'Default', 'title': 'Doraemon Movie ...",Doraemon Movie 45: Shin Nobita no Kaitei Kiganjou,Doraemon the Movie 2026: New Nobita and the Ca...,映画ドラえもん 新・のび太の海底鬼岩城,[],...,None,NaN,"{'day': None, 'time': None, 'timezone': None, ...",[],[],"[{'mal_id': 247, 'type': 'anime', 'name': 'Shi...","[{'mal_id': 4, 'type': 'anime', 'name': 'Comed...",[],"[{'mal_id': 51, 'type': 'anime', 'name': 'Anth...","[{'mal_id': 15, 'type': 'anime', 'name': 'Kids..."
24,62277,https://myanimelist.net/anime/62277/Gintama_Mo...,{'jpg': {'image_url': 'https://myanimelist.net...,"{'youtube_id': None, 'url': None, 'embed_url':...",True,"[{'type': 'Default', 'title': 'Gintama Movie 3...",Gintama Movie 3: Yoshiwara Daienjou,None,新劇場版 銀魂 -吉原大炎上-,[Gintama Movie 3: Yoshiwara in Flames],...,None,NaN,"{'day': None, 'time': None, 'timezone': None, ...","[{'mal_id': 1889, 'type': 'anime', 'name': 'Wa...",[],"[{'mal_id': 1258, 'type': 'anime', 'name': 'Ba...","[{'mal_id': 1, 'type': 'anime', 'name': 'Actio...",[],"[{'mal_id': 57, 'type': 'anime', 'name': 'Gag ...","[{'mal_id': 27, 'type': 'anime', 'name': 'Shou..."